# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hek8s Terraform Azure!l
  displayName: 'Run a one-line script'

- task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@1
  inputs:
    terraformVersion: '1.5.7'

- script: terraform version
  displayName: 'Verify Terraform Installation'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_piblic_key=$(publickey.secureFilePath)'
    backendType: 'azurerm'
    backendServiceArm: 'sc-azure-resourcemanager'
    backendAzureRmTenantId: 'd5d40ca8-b5aa-4d8f-8272-407b515cb5a7'
    backendAzureRmSubscriptionId: 'ee319277-edaa-4c07-9b91-04d1eb7bf895'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'RG-terraform-aksbuid-001'
    backendAzureRmResourceGroupLocation: 'east us'
    backendAzureRmStorageAccountName: 'stfirstterraformaks001'
    backendAzureRmContainerName: 'containerterraform-aks'
    backendAzureRmKey: 'kubernetes-dev.tfstate'
    allowTelemetryCollection: true



